server:
  port: 9999

spring:
  application:
    name: api-gateway-service
  output:
    ansi:
      enabled: ALWAYS
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true

eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      default-zone: http://localhost:8761/eureka

jwt:
  secret: sdsdsdswuquiqwiqeregsaghaghstyqttyqyteqtyetqtyety
  expiration: 86400000

logging:
  level:
    org.springframework.web.HttpLogging: TRACE
    reactor.netty.http.server: DEBUG
    reactor.netty.http.client: DEBUG

