server:
  port: 8500

spring:
  application:
    name: api-gateway-service
  output:
    ansi:
      enabled: ALWAYS

eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      default-zone: http://localhost:8761/eureka


######AUTH SERVER#############
auth:
  serviceid: auth-service