server:
  port: 9999

spring:
  application:
    name: api-gateway-service
  output:
    ansi:
      enabled: ALWAYS

  #  cloud:
  #    gateway:
  #      routes:
  #        - id: user-service
  #          uri: lb://user-service
  #          predicates:
  #            - Path=/auth/**, /howdy/**
  #
  #        - id: order-service
  #          uri: lb://order-service
  #          predicates:
  #            - Path=/orders/**
  #
  #        - id: course-service
  #          uri: lb://course-service
  #          predicates:
  #            - Path=/course/**

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: user-service
          uri: lb:http://USER-SERVICE
          predicates:
            - Path=/auth/**, /howdy/**

        - id: order-service
          uri: lb:http://ORDER-SERVICE
          predicates:
            - Path=/orders/**

        - id: course-service
          uri: lb:http://COURSE-SERVICE
          predicates:
            - Path=/course/**

eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      default-zone: http://localhost:8761/eureka



