server:
  port: 8761

spring:
  application:
    name: discovery-server

  output:
    ansi:
      enabled: ALWAYS

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      default-zone: http://localhost:8761/eureka