server:
  port: 9997

spring:
  application:
    name: order-service

  output:
    ansi:
      enabled: ALWAYS

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    url: jdbc:mysql://localhost:3306/order_db?createDatabaseIfNotExist=true
    password: 0003pray

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        hbm2ddl.auto: update
        format_sql: true
        show_sql: true

  security:
    method:
      pre-post-enabled: true
      jsr250-enabled: true

eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      default-zone: http://localhost:8761/eureka

jwt:
  secret: yeuwye2732673habdhghdgshdghsghdgshdghsgdhgshdghsgdhshdghsgdsgdgshdghsgdhsgdhgsdghsgh
  expiration: 86400000






