server:
  port: 8700
  servlet:
    context-path: /api/v1

spring:
  application:
    name: client-service
  output:
    ansi:
      enabled: ALWAYS

app:
  auth:
    jwt.secret: test
    role.allowed: ROLE_USER

eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      default-zone: http://localhost:8761/eureka

