server:
  port: 9998

spring:
  application:
    name: notification-service
  output:
    ansi:
      enabled: ALWAYS
  activemq:
    broker-url: tcp://localhost:61617
    password: admin
    user: admin

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/


