spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: javatechie


  kafka:
    bootstrap-servers: localhost:9092   # Kafka broker addresses
    consumer:
      group-id: shipping-service    # Group ID for the consumer
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer  # Deserializer for the key
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer  # Wraps JsonDeserializer for error handling
      properties:
        spring.deserializer.key.delegate.class: org.apache.kafka.common.serialization.StringDeserializer
        spring.deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JsonDeserializer
        spring.json.trusted.packages: "*"

shipping:
  event:
    topicName: shipping-events