server:
  port: 9999

spring:
  application:
    name: AUTH-SERVICE

  output:
    ansi:
      enabled: ALWAYS

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/user_db?createDatabaseIfNotExist=true
    username: root
    password: 0003pray

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    properties:
      hibernate.format_sql: true
      hibernate.show_sql: true
      hibernate.hbm2ddl.auto: update
      hibernate.dialect: org.hibernate.dialect.MySQL8Dialect

eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      default-zone: http://localhost:8761/eureka

jwt:
  secret: 98qiweyqaeyqieqiqeqieuiqueiquueqieiqueiuqiueuiquiaeui
  prefix: Bearer
  expiration: 3600000  # 1 hour in milliseconds
