server.port: 8060

spring:
  application:
    name: API-GATEWAY-SERVICE
  cloud:
    gateway:
      default-filters:
        - TokenRelay=
      routes:
        - id: USER-SERVICE
          uri: lb://USER-SERVICE
          predicates:
              - Path=/users/**

        - id: HOTEL-SERVICE
          uri: lb://HOTEL-SERVICE
          predicates:
            - Path=/hotels/**,/staffs/**

        - id: RATING-SERVICE
          uri: lb://RATING-SERVICE
          predicates:
            - Path=/ratings/**

  config:
    import: optional:configserver:http://localhost:8085

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8080/realms/demo/protocol/openid-connect/certs
      client:
        provider:
          keycloak:
            issuer-uri: http://localhost:8080/realms/demo
        registration:
          spring-with-test-scope:
            provider: keycloak
            client-id: spring-with-test-scope
            client-secret: W4xt7ER6l24DxPGLfzbLhdl0WgvLt10Z
            authorization-grant-type: authorization_code
            scope: openid

logging.level:
  org.springframework.cloud.gateway: DEBUG
  org.springframework.security: DEBUG
  org.springframework.web.reactive.function.client: TRACE
