server:
  port: 9998

spring:
  application:
    name: notification-service
  output:
    ansi:
      enabled: ALWAYS
  rabbitmq:
    addresses: localhost:5672

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

